version: "3"
services:
  app:
    build: .
    ports:
      - "1337:80" # host:container
    volumes:
      - .:/opt/app
      # Hack for excluding node_modules
      - /opt/app/node_modules/
    entrypoint:
      - npm
      - run
      - serve
